version: 0.0
os: linux
files:
  - source: /
    destination: /home/webapp/laravel-aws-ec2-cicd

permissions:
  - object: /home/webapp/laravel-aws-ec2-cicd
    owner: webapp
    group: webapp

hooks:
  AfterInstall:
    - location: ./scripts/after_install.sh
      timeout: 360
      runas: webapp